from seizcord import setHypeSquad
from seizcord import enableDevMode
from seizcord import disableDevMode
from seizcord import setTheme
from seizcord import changeLanguage
from seizcord import disableFriendsRequests
from seizcord import enableFriendsRequests
from seizcord import enableCompactMode
from seizcord import disableCompactMode
from seizcord import blockUser
from seizcord import unblockUser
from seizcord import leaveGuild
from seizcord import SendMessage